services:
  - type: web
    name: tehri-map-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: java -jar app.jar
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://parasstarkmarkup:DKvIzrVeJgR1nrwX@cluster0.cr8izeq.mongodb.net/authdb?retryWrites=true&w=majority
      - key: MONGODB_DATABASE
        value: authdb
      - key: JWT_SECRET
        value: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /api/health
    autoDeploy: true 